[package]
name = "ipv8-forward"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
ipv8-firewall = { path = "../../core/ipv8-firewall" }
ipv8-codec = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
