# IPv8+ Address Allocation Manager
# Manages IPv8 address pool, assigns addresses to connecting clients

$allocations = @{}
$nextClient = 2  # Start from 2 (1 = server)
$lock = [System.Threading.Mutex]::new($false, "IPv8AllocLock")

function Get-ServerIPv6 {
    try {
        $addrs = Get-NetIPAddress -AddressFamily IPv6 -ErrorAction Stop |
            Where-Object { $_.IPAddress -notlike "fe80::*" -and $_.IPAddress -notlike "::1" -and $_.PrefixOrigin -eq "RouterAdvertisement" }
        if ($addrs) { return ($addrs | Select-Object -First 1).IPAddress }
    } catch {}
    return $null
}

function Allocate-IPv8Address {
    param([string]$clientIp, [string]$clientName = "")
    
    $lock.WaitOne() | Out-Null
    try {
        # Check if already allocated
        $existing = $allocations.Values | Where-Object { $_.client_ip -eq $clientIp }
        if ($existing) {
            return $existing
        }
        
        # Generate new address: fb14:0000:0000:0001:0001:0000:{clientNum:0000}:0000
        $clientNum = $nextClient
        $nextClient++
        
        $hex = "{0:x4}" -f $clientNum
        $ipv8Addr = "fb14:0000:0000:0001:0001:0000:$hex`:0000"
        $ipv8Compact = "fb14::1:$hex`0"
        
        $record = @{
            ipv8_address = $ipv8Addr
            ipv8_compact = "fb14::$(100 + $clientNum)"
            tun_ip = "100.64.0.$clientNum"
            client_ip = $clientIp
            client_name = if ($clientName) { $clientName } else { "client-$clientNum" }
            assigned_at = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
            status = "active"
        }
        
        $allocations[$clientNum] = $record
        return $record
    }
    finally {
        $lock.ReleaseMutex()
    }
}

function Get-AllAllocations {
    $lock.WaitOne() | Out-Null
    try {
        return $allocations.Values | Sort-Object { $_.assigned_at }
    }
    finally {
        $lock.ReleaseMutex()
    }
}

function Release-IPv8Address {
    param([string]$clientIp)
    
    $lock.WaitOne() | Out-Null
    try {
        $existing = $allocations.Values | Where-Object { $_.client_ip -eq $clientIp }
        if ($existing) {
            $existing.status = "released"
            $existing.released_at = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
        }
    }
    finally {
        $lock.ReleaseMutex()
    }
}

function Get-ClientConfig {
    param([object]$alloc)
    
    $serverIPv6 = Get-ServerIPv6
    
    # Generate client config that auto-connects to this server
    $config = @"
# IPv8+ Client Auto-Config
# Auto-generated by IPv8+ Portal
# Do not edit - this file is regenerated on each connection

server_ipv8 = $($alloc.ipv8_address -replace ':','')
server_ipv6 = $serverIPv6
server_domain = ipv8.yulaoshi.xyz
server_udp_port = 45700

client_ipv8 = $($alloc.ipv8_address)
client_tun_ip = $($alloc.tun_ip)
client_tun_prefix = 10

adapter_name = IPv8Plus
mtu = 1432

# GeoIP info
country = China
province = Jiangxi
city = Jiujiang
isp = China Mobile
asn = AS9808
"@
    return $config
}

function Build-ClientLauncher {
    param([object]$alloc)
    
    $serverIPv6 = Get-ServerIPv6
    if (-not $serverIPv6) { $serverIPv6 = "ipv8.yulaoshi.xyz" }
    
    $selfHex = ($alloc.ipv8_address -replace ':','').PadRight(32, '0').Substring(0, 32)
    
    # Server address is fb14:...000a... (server = node A)
    $peerHex = "0000fb140000000a0001000001000000"
    
    $psScript = @"
# IPv8+ Auto-Connect Client
# Generated by IPv8+ Portal - yulaoshi.xyz
# Just run this script as Administrator - it handles everything else.

`$exe = Join-Path `$PSScriptRoot 'ipv8-node.exe'
`$dll = Join-Path `$PSScriptRoot 'wintun.dll'

if (-not (Test-Path `$exe)) {
    Write-Host "ERROR: ipv8-node.exe not found. Download it from https://ipv8.yulaoshi.xyz" -ForegroundColor Red
    Read-Host "Press Enter to close"
    exit 1
}

# Auto-elevate
`$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not `$isAdmin) {
    Write-Host "Requesting admin privileges..." -ForegroundColor Yellow
    Start-Process powershell -Verb RunAs -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"`$PSCommandPath`"" -Wait
    exit
}

Write-Host "=== IPv8+ Client Starting ===" -ForegroundColor Cyan
Write-Host "Server: $serverIPv6 (ipv8.yulaoshi.xyz)" -ForegroundColor Green
Write-Host "Your IPv8: $($alloc.ipv8_compact)" -ForegroundColor Green
Write-Host "Your TUN IP: $($alloc.tun_ip)" -ForegroundColor Green
Write-Host ""

# Copy wintun.dll if missing
if (-not (Test-Path `$dll) -and (Test-Path (Join-Path `$PSScriptRoot '..\wintun.dll'))) {
    Copy-Item (Join-Path `$PSScriptRoot '..\wintun.dll') `$dll -Force
}

# Firewall rule
New-NetFirewallRule -Name "IPv8Plus-Client" -DisplayName "IPv8+ Client UDP 45700" `
    -Direction Inbound -Action Allow -Protocol UDP -LocalPort 45700 -Profile Any `
    -ErrorAction SilentlyContinue | Out-Null

# Start ipv8-node with auto-config
`$args = @(
    '--self', '$selfHex',
    '--peer-addr', '$peerHex',
    '--peer-ip', '$serverIPv6',
    '--peer-port', '45700',
    '--udp-port', '45700',
    '--tun-ip', '$($alloc.tun_ip)',
    '--tun-prefix', '10',
    '--adapter-name', 'IPv8Plus',
    '--initiate',
    '--auth',
    '--ca-seed', 'C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4C4'
)

Write-Host "Connecting to server..." -ForegroundColor Yellow
& `$exe @args
"@
    return $psScript
}
